# Import Libaries

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# Load Dataset

In [2]:
df=pd.read_csv("vaccination-data.csv")

# Data Exploration

In [3]:
df.head()

,COUNTRY,ISO3,WHO_REGION,DATA_SOURCE,DATE_UPDATED,TOTAL_VACCINATIONS,PERSONS_VACCINATED_1PLUS_DOSE,TOTAL_VACCINATIONS_PER100,PERSONS_VACCINATED_1PLUS_DOSE_PER100,PERSONS_FULLY_VACCINATED,PERSONS_FULLY_VACCINATED_PER100,VACCINES_USED,FIRST_VACCINE_DATE,NUMBER_VACCINES_TYPES_USED
0,Afghanistan,AFG,EMRO,REPORTING,8/30/2021,1979652,773002.0,5.09,1.99,441371.0,1.13,"Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2...",2/22/2021,4.0
1,Albania,ALB,EURO,OWID,8/30/2021,1458048,824170.0,50.67,28.64,633878.0,22.03,"AstraZeneca - AZD1222, Pfizer BioNTech - Comir...",NaN,4.0
2,Algeria,DZA,AFRO,REPORTING,8/23/2021,4146091,3421279.0,9.46,7.80,724812.0,1.65,"Beijing CNBG - BBIBP-CorV,Gamaleya - Sputnik V...",1/30/2021,3.0
3,American Samoa,ASM,WPRO,REPORTING,8/20/2021,54425,29993.0,98.60,54.34,24977.0,45.25,"Janssen - Ad26.COV 2.5,Moderna - mRNA-1273,Pfi...",12/21/2020,3.0
4,Andorra,AND,EURO,OWID,8/15/2021,91660,51044.0,118.63,66.06,40616.0,52.57,"AstraZeneca - AZD1222, Pfizer BioNTech - Comir...",NaN,2.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 14 columns):
COUNTRY                                 227 non-null object
ISO3                                    227 non-null object
WHO_REGION                              227 non-null object
DATA_SOURCE                             227 non-null object
DATE_UPDATED                            227 non-null object
TOTAL_VACCINATIONS                      227 non-null int64
PERSONS_VACCINATED_1PLUS_DOSE           220 non-null float64
TOTAL_VACCINATIONS_PER100               227 non-null float64
PERSONS_VACCINATED_1PLUS_DOSE_PER100    220 non-null float64
PERSONS_FULLY_VACCINATED                219 non-null float64
PERSONS_FULLY_VACCINATED_PER100         219 non-null float64
VACCINES_USED                           223 non-null object
FIRST_VACCINE_DATE                      156 non-null object
NUMBER_VACCINES_TYPES_USED              223 non-null float64
dtypes: float64(6), int64(1), object(7)
memory usage: 25.0+ KB

In [5]:
df.describe()

,TOTAL_VACCINATIONS,PERSONS_VACCINATED_1PLUS_DOSE,TOTAL_VACCINATIONS_PER100,PERSONS_VACCINATED_1PLUS_DOSE_PER100,PERSONS_FULLY_VACCINATED,PERSONS_FULLY_VACCINATED_PER100,NUMBER_VACCINES_TYPES_USED
count,2.270000e+02,2.200000e+02,227.000000,220.000000,2.190000e+02,219.000000,223.000000
mean,2.330275e+07,9.131548e+06,68.648282,37.736182,5.511441e+06,29.989132,3.237668
std,1.449239e+08,3.880327e+07,52.998231,27.106529,1.787370e+07,25.378871,1.719527
min,7.300000e+01,0.000000e+00,0.110000,0.000000,3.600000e+01,0.020000,1.000000
25%,1.283870e+05,7.461725e+04,18.430000,12.307500,4.143200e+04,5.940000,2.000000
50%,1.045074e+06,6.087465e+05,62.790000,35.340000,3.817910e+05,25.040000,3.000000
75%,7.763394e+06,4.237226e+06,117.080000,62.492500,2.874100e+06,53.445000,4.000000
max,2.040872e+09,5.009039e+08,234.050000,117.630000,1.727310e+08,116.430000,9.000000

In [6]:
df.describe(include="all")

,COUNTRY,ISO3,WHO_REGION,DATA_SOURCE,DATE_UPDATED,TOTAL_VACCINATIONS,PERSONS_VACCINATED_1PLUS_DOSE,TOTAL_VACCINATIONS_PER100,PERSONS_VACCINATED_1PLUS_DOSE_PER100,PERSONS_FULLY_VACCINATED,PERSONS_FULLY_VACCINATED_PER100,VACCINES_USED,FIRST_VACCINE_DATE,NUMBER_VACCINES_TYPES_USED
count,227,227,227,227,227,2.270000e+02,2.200000e+02,227.000000,220.000000,2.190000e+02,219.000000,223,156,223.000000
unique,227,227,7,2,25,NaN,NaN,NaN,NaN,NaN,NaN,106,94,NaN
top,Saint Lucia,ISL,EURO,REPORTING,8/27/2021,NaN,NaN,NaN,NaN,NaN,NaN,"Janssen - Ad26.COV 2.5, Moderna - mRNA-1273, A...",2/17/2021,NaN
freq,1,1,60,165,63,NaN,NaN,NaN,NaN,NaN,NaN,20,7,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.330275e+07,9.131548e+06,68.648282,37.736182,5.511441e+06,29.989132,NaN,NaN,3.237668
std,NaN,NaN,NaN,NaN,NaN,1.449239e+08,3.880327e+07,52.998231,27.106529,1.787370e+07,25.378871,NaN,NaN,1.719527
min,NaN,NaN,NaN,NaN,NaN,7.300000e+01,0.000000e+00,0.110000,0.000000,3.600000e+01,0.020000,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,1.283870e+05,7.461725e+04,18.430000,12.307500,4.143200e+04,5.940000,NaN,NaN,2.000000
50%,NaN,NaN,NaN,NaN,NaN,1.045074e+06,6.087465e+05,62.790000,35.340000,3.817910e+05,25.040000,NaN,NaN,3.000000
75%,NaN,NaN,NaN,NaN,NaN,7.763394e+06,4.237226e+06,117.080000,62.492500,2.874100e+06,53.445000,NaN,NaN,4.000000
max,NaN,NaN,NaN,NaN,NaN,2.040872e+09,5.009039e+08,234.050000,117.630000,1.727310e+08,116.430000,NaN,NaN,9.000000

In [7]:
df.shape

(227, 14)

# Data cleaning

In [8]:
col=df.columns

## Find missinng values

In [9]:
for i in col:
    print(df[i].isnull().value_counts())
    print("")

False    227
Name: COUNTRY, dtype: int64

False    227
Name: ISO3, dtype: int64

False    227
Name: WHO_REGION, dtype: int64

False    227
Name: DATA_SOURCE, dtype: int64

False    227
Name: DATE_UPDATED, dtype: int64

False    227
Name: TOTAL_VACCINATIONS, dtype: int64

False    220
True       7
Name: PERSONS_VACCINATED_1PLUS_DOSE, dtype: int64

False    227
Name: TOTAL_VACCINATIONS_PER100, dtype: int64

False    220
True       7
Name: PERSONS_VACCINATED_1PLUS_DOSE_PER100, dtype: int64

False    219
True       8
Name: PERSONS_FULLY_VACCINATED, dtype: int64

False    219
True       8
Name: PERSONS_FULLY_VACCINATED_PER100, dtype: int64

False    223
True       4
Name: VACCINES_USED, dtype: int64

False    156
True      71
Name: FIRST_VACCINE_DATE, dtype: int64

False    223
True       4
Name: NUMBER_VACCINES_TYPES_USED, dtype: int64

## Copy dataset

In [10]:
data=df[['COUNTRY','TOTAL_VACCINATIONS', 'PERSONS_VACCINATED_1PLUS_DOSE',
       'TOTAL_VACCINATIONS_PER100', 'PERSONS_VACCINATED_1PLUS_DOSE_PER100',
       'PERSONS_FULLY_VACCINATED', 'PERSONS_FULLY_VACCINATED_PER100',
       'VACCINES_USED', 'NUMBER_VACCINES_TYPES_USED']].copy()

# Remove null values

In [11]:
data.dropna(axis=0,inplace=True)

In [12]:
data.shape

(213, 9)

# Verify changes

In [13]:
col=data.columns
for i in col:
    print(data[i].isnull().value_counts())
    print("")

False    213
Name: COUNTRY, dtype: int64

False    213
Name: TOTAL_VACCINATIONS, dtype: int64

False    213
Name: PERSONS_VACCINATED_1PLUS_DOSE, dtype: int64

False    213
Name: TOTAL_VACCINATIONS_PER100, dtype: int64

False    213
Name: PERSONS_VACCINATED_1PLUS_DOSE_PER100, dtype: int64

False    213
Name: PERSONS_FULLY_VACCINATED, dtype: int64

False    213
Name: PERSONS_FULLY_VACCINATED_PER100, dtype: int64

False    213
Name: VACCINES_USED, dtype: int64

False    213
Name: NUMBER_VACCINES_TYPES_USED, dtype: int64

# Save Dataset

In [18]:
data.to_csv("covid_vaccines_.csv")